package golidators

import "testing"

var UrlCases = [118]StrTestRecord{
	StrTestRecord{"http://foobar.dk", true},
	StrTestRecord{"http://foobar.museum/foobar", true},
	StrTestRecord{"http://fo.com", true},
	StrTestRecord{"http://www.google.com", true},
	StrTestRecord{"ftp://www.test.co/", true},
	StrTestRecord{"https://www.facebook.com/", true},
	StrTestRecord{"http://FOO.com", true},
	StrTestRecord{"http://foo.com/blah_blah", true},
	StrTestRecord{"http://foo.com/blah_blah/", true},
	StrTestRecord{"http://foo.com/blah_blah_(wikipedia)", true},
	StrTestRecord{"http://foo.com/blah_blah_(wikipedia)_(again)", true},
	StrTestRecord{"http://www.example.com/wpstyle/?p=364", true},
	StrTestRecord{"https://www.example.com/foo/?bar=baz&inga=42&quux", true},
	StrTestRecord{"https://www.example.com?bar=baz", true},
	StrTestRecord{"http://✪df.ws/123", true},
	StrTestRecord{"http://www.test.co?id=2&q=test#asdasda", true},
	StrTestRecord{"http://userid:password@example.com:8080", true},
	StrTestRecord{"http://userid:password@example.com:8080/", true},
	StrTestRecord{"http://userid@example.com", true},
	StrTestRecord{"http://userid@example.com/", true},
	StrTestRecord{"http://userid@example.com:8080", true},
	StrTestRecord{"http://userid@example.com:8080/", true},
	StrTestRecord{"http://userid:password@example.com", true},
	StrTestRecord{"http://userid:password@example.com/", true},
	StrTestRecord{"http://142.42.1.1/", true},
	StrTestRecord{"http://142.42.1.1:8080/", true},
	StrTestRecord{"http://➡.ws/䨹", true},
	StrTestRecord{"http://⌘.ws", true},
	StrTestRecord{"http://⌘.ws/", true},
	StrTestRecord{"http://foo.com/blah_(wikipedia)#cite-1", true},
	StrTestRecord{"http://foo.com/blah_(wikipedia)_blah#cite-1", true},
	StrTestRecord{"http://foo.com/unicode_(✪)_in_parens", true},
	StrTestRecord{"http://foo.com/(something)?after=parens", true},
	StrTestRecord{"http://☺.damowmow.com/", true},
	StrTestRecord{"http://code.google.com/events/#&product=browser", true},
	StrTestRecord{"http://j.mp", true},
	StrTestRecord{"ftp://foo.bar/baz", true},
	StrTestRecord{"http://foo.bar/?q=Test%20URL-encoded%20stuff", true},
	StrTestRecord{"http://مثال.إختبار", true},
	StrTestRecord{"http://例子.测试", true},
	StrTestRecord{"http://उदाहरण.परीक्षा", true},
	StrTestRecord{"http://www.😉.com", true},
	StrTestRecord{"http://😉.com/😁", true},
	StrTestRecord{"http://উদাহরণ.বাংলা", true},
	StrTestRecord{"http://xn--d5b6ci4b4b3a.xn--54b7fta0cc", true},
	StrTestRecord{"http://-.~_!$&'()*+,;=:%40:80%2f::::::@example.com", true},
	StrTestRecord{"http://1337.net", true},
	StrTestRecord{"http://a.b-c.de", true},
	StrTestRecord{"http://223.255.255.254", true},
	StrTestRecord{"http://10.1.1.0", true},
	StrTestRecord{"http://10.1.1.1", true},
	StrTestRecord{"http://10.1.1.254", true},
	StrTestRecord{"http://10.1.1.255", true},
	StrTestRecord{"http://127.0.0.1:8080", true},
	StrTestRecord{"http://127.0.10.150", true},
	StrTestRecord{"http://localhost", true},
	StrTestRecord{"http://localhost:8000", true},
	StrTestRecord{"http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html", true},
	StrTestRecord{"http://[1080:0:0:0:8:800:200C:417A]/index.html", true},
	StrTestRecord{"http://[3ffe:2a00:100:7031::1]", true},
	StrTestRecord{"http://[1080::8:800:200C:417A]/foo", true},
	StrTestRecord{"http://[::192.9.5.5]/ipng", true},
	StrTestRecord{"http://[::FFFF:129.144.52.38]:80/index.html", true},
	StrTestRecord{"http://[2010:836B:4179::836B:4179]", true},
	StrTestRecord{"", false},
	StrTestRecord{"google.com", false},
	StrTestRecord{"www.google.com", false},
	StrTestRecord{"çç3#>#>£#>{¾[¾{]âßâ¢ß", false},
	StrTestRecord{"http://http://asdad.com/?id=2", false},
	StrTestRecord{"\" 'test')\"", false},
	StrTestRecord{"http://foobar", false},
	StrTestRecord{"http://127.0.0/asdf", false},
	StrTestRecord{"http://foobar.d", false},
	StrTestRecord{"http://foobar.12", false},
	StrTestRecord{"http://foobar", false},
	StrTestRecord{"htp://foobar.com", false},
	StrTestRecord{"http://foobar..com", false},
	StrTestRecord{"http://fo..com", false},
	StrTestRecord{"http://", false},
	StrTestRecord{"http://.", false},
	StrTestRecord{"http://..", false},
	StrTestRecord{"http://../", false},
	StrTestRecord{"http://?", false},
	StrTestRecord{"http://??", false},
	StrTestRecord{"http://??/", false},
	StrTestRecord{"http://#", false},
	StrTestRecord{"http://##", false},
	StrTestRecord{"http://##/", false},
	StrTestRecord{"http://foo.bar?q=Spaces should be encoded", false},
	StrTestRecord{"//", false},
	StrTestRecord{"//a", false},
	StrTestRecord{"///a", false},
	StrTestRecord{"///", false},
	StrTestRecord{"http:///a", false},
	StrTestRecord{"foo.com", false},
	StrTestRecord{"rdar://1234", false},
	StrTestRecord{"h://test", false},
	StrTestRecord{"http:// shouldfail.com", false},
	StrTestRecord{":// should fail", false},
	StrTestRecord{"http://foo.bar/foo(bar)baz quux", false},
	StrTestRecord{"ftps://foo.bar/", false},
	StrTestRecord{"http://-error-.invalid/", false},
	StrTestRecord{"http://a.b--c.de/", false},
	StrTestRecord{"http://-a.b.co", false},
	StrTestRecord{"http://a.b-.co", false},
	StrTestRecord{"http://0.0.0.0", false},
	StrTestRecord{"http://224.1.1.1", false},
	StrTestRecord{"http://1.1.1.1.1", false},
	StrTestRecord{"http://123.123.123", false},
	StrTestRecord{"http://3628126748", false},
	StrTestRecord{"http://.www.foo.bar/", false},
	StrTestRecord{"http://www.foo.bar./", false},
	StrTestRecord{"http://.www.foo.bar./", false},
	StrTestRecord{"http://127.12.0.260", false},
	StrTestRecord{"http://example.com/\">user@example.com", false},
	StrTestRecord{"http://[2010:836B:4179::836B:4179", false},
	StrTestRecord{"http://2010:836B:4179::836B:4179", false},
	StrTestRecord{"http://2010:836B:4179::836B:4179:80/index.html", false},
}

func TestUrl(t *testing.T) {
	for _, record := range UrlCases {
		if Url(record.TargetValue) != record.Expected {
			t.Error(record.TargetValue)
		}
	}
}
